### ISSUE TITLE
LDAP filter not customisable or filter not suitable

### ISSUE THREAD

**Issue by datango** [HAWK-Digital-Environments/HAWKI#58]
Current LDAP filter:

https://github.com/HAWK-Digital-Environments/HAWKI/blob/6cacf51dbc4bd9f1e6f02b390d0fd2955a8b7f66/private/app/php/auth.php#L90

We need to filter by person uid, like it was before last update.

Please make the LDAP filter configurable.

**Comment by Ariansdf** [comment]
@datango 
I'm not sure if you're referring to a relatively old commit with this filter?

`$sanitizedUsername = ldap_escape($username, "", LDAP_ESCAPE_FILTER);`
`$filter = "(|(uid=$sanitizedUsername)(mail=$sanitizedUsername))";`

I double checked our older commits and the filter has not been changed since at least the last update:

`$filter = "(|(sAMAccountName=$username)(mail=$username))";`

could your problem is related to this line in auth.php?

137 `$username = filter_var($_POST["account"], FILTER_UNSAFE_RAW);`

you can try to comment this line out, or try to replace the current filter with the older one and see if it works.
Please let me know if it solved the issue.

**Comment by datango** [comment]
No, my link to line 90 is of the current main branch.

My problem has nothing to do with line 137.

The ldap login works, if i change line 90 
from 
$filter = "(|(sAMAccountName=$username)(mail=$username))"; 
to 
$filter = "(|(uid=$username)(mail=$username))";

because we dont use active directory and we don't use the mail address as username. We want to use the uid.

**Comment by Ariansdf** [comment]
thank you for letting me know.
I'll prepare a patch in the future.
